name = "dronescout-proxy"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# Your API token will be stored as a secret (not in this file)
# Set it with: wrangler secret put SKYDIO_API_TOKEN
# Paste your token when prompted: dd2aa817ea72a66dc303fd5c8b441f73676cf06e9d09bfafa46016ce08907d48

[env.production]
name = "dronescout-proxy"
