name = "dronescout-proxy"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# Your API token will be stored as a secret (not in this file)
# Set it with: wrangler secret put SKYDIO_API_TOKEN
# IMPORTANT: Use the token SECRET (64-char hex), not the token ID (UUID)
# v1 API requires Organization API tokens with Read permissions for Flights, Telemetry, and Media
# Token exposed in git history - REVOKE old tokens and create new one

[env.production]
name = "dronescout-proxy"
